export const environment = {
  production: true,
  // API_BASE_URL: 'http://baiwa.ddns.net:9440',
  // API_URL: 'http://baiwa.ddns.net:9440/COFFEE/api',
  // API_MAIN: 'http://baiwa.ddns.net:9440/COFFEE/',
  // API_BEAN_URL: 'http://baiwa.ddns.net:9440/coffee-beans/api',
  // API_BEAN_MAIN: 'http://baiwa.ddns.net:9440/coffee-beans/',
  // FILE_UPLOAD_URL: '',
  // IMG_URL: '',

  // API_BASE_URL: 'https://finnbet.com',
  // API_URL: 'https://finnbet.com/backoffice/api',
  // API_MAIN: 'https://finnbet.com/backoffice/',
  // API_IMG_URL: 'http://finnbet.com/COFFEE-FILE/api',
  // API_IMG_MAIN: 'http://finnbet.com/COFFEE-FILE/',
  // API_BEAN_URL: 'https://finnbet.com/coffee-beans/api',
  // API_BEAN_MAIN: 'https://finnbet.com/coffee-beans/',
  // API_WEBPLAYER_URL: 'https://finnbet.com/backoffice/api',
  // API_WEBPLAYER_MAIN: 'https://finnbet.com/backoffice/',
  // FILE_UPLOAD_URL: '',
  // IMG_URL: '',
  // API_BEAN_SOCKET: 'wss://finnbet.com/coffee-beans/socket',
  // API_BEAN_SOCKET: 'ws://172.19.93.12:8080/coffee-beans/socket',

  API_BASE_URL: 'http://localhost:8080',
  API_URL: 'http://localhost:8080/COFFEE/api',
  // API_MAIN: 'http://localhost:8080/COFFEE/',
  // API_URL: 'https://finnbet.com/COFFEE/api',
  // API_MAIN: 'https://finnbet.com/COFFEE/',

  API_IMG_URL: 'http://localhost:8084/COFFEE-FILE/api',
  API_IMG_MAIN: 'http://localhost:8084/COFFEE-FILE/',
  API_BEAN_URL: 'http://localhost:8082/coffee-beans/api',
  API_BEAN_MAIN: 'http://localhost:8082/coffee-beans/',
  API_WEBPLAYER_URL: 'http://localhost:8080/COFFEE/api',
  API_WEBPLAYER_MAIN: 'http://localhost:8080/COFFEE/',
  FILE_UPLOAD_URL: '',
  API_BEAN_SOCKET: 'ws://172.19.50.118:8082/coffee-beans/socket',
  DEBUG_SOCKET: true,
  // DEBUG_SOCKET: false,
};
